apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dx9iee49p-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dx9iee49p-python 
  name: dx9iee49p-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dx9iee49p-python 
